### ISSUE TITLE
mSenseMgr->Init(); returns PXC_STATUS_ITEM_UNAVAILABLE in all examples

### ISSUE THREAD

**Issue by joshuajnoble** [SethGibson/ofxRSSDKv2#1]
Oddly `mSenseMgr->EnableStream(PXCCapture::STREAM_TYPE_DEPTH,...)` and `mSenseMgr->EnableStream(PXCCapture::STREAM_TYPE_COLOR,...)` both report back no error and all of the samples with the SDK download build and run fine. I'm using the F200 on Visual Studio 2013. Any information I could send to help you debug?

**Comment by SethGibson** [comment]
I think this actually might have to do with a recent SDK change that's been breaking things, let me update and see what's going on there.

**Comment by joshuajnoble** [comment]
Never mind, this was as easy changing the init params to:

```
        mRSSDK->initDepth(DepthRes::F200_VGA, 30, true);
        mRSSDK->initRgb(RGBRes::HD720, 30);

```

Might be a good idea to put a define in the header for the type of device?

**Comment by SethGibson** [comment]
Good call, will add that to the samples. Thanks for the catch, let me know if there are any specific features you'd like to see implemented.
