### ISSUE TITLE
Examples are not showing streams

### ISSUE THREAD

**Issue by wandergeek** [SethGibson/ofxRSSDKv2#2]
The simple example shows blank textures when it is run. I've discovered that the mSenseMgr->Init() function in the RS Device init returns PXC_STATUS_ITEM_UNAVAILABLE. Since the return is not checked, the program continues normally and blank textures are drawn. The RealSense SDK examples run fine. Depth, IR, and RGB feeds come through normally.

I'm running the latest master of OF (266c336cf2df6ac23e0729136663b46a6aeacaa5), the latest RealSense SDK (6.0.21.6598) , and the camera is running firmare 2.60.0.0. I'm building the project in VS2015,

 I suspect the issue is that I have a newer SDK than when this was created. Can you assist me?

Thanks for your time!

**Comment by KavinHan** [comment]
I have same problem.
When u change EnableStream code u can show stream. (I don'nt know why...just flow example source code. =,=)

file: ofxRSSDKv2.cpp =>
line 50: 
```
cStatus = mSenseMgr->EnableStream(PXCCapture::STREAM_TYPE_COLOR, mRgbSize.x, mRgbSize.y, pFPS);
````
command this line:
```
//cStatus = mSenseMgr->EnableStream(PXCCapture::STREAM_TYPE_COLOR, mRgbSize.x, mRgbSize.y, pFPS);
```
add add this code:
```
PXCVideoModule::DataDesc desc = {};
desc.streams[PXCCapture::STREAM_TYPE_COLOR].frameRate.min = pFPS;
desc.streams[PXCCapture::STREAM_TYPE_COLOR].sizeMin.height = mRgbSize.y;
desc.streams[PXCCapture::STREAM_TYPE_COLOR].sizeMin.width = mRgbSize.x;
cStatus = mSenseMgr->EnableStreams(&desc);
```
then u can get color stream.

file: ofxRSSDKv2.cpp =>
line 86: 
```
cStatus = mSenseMgr->EnableStream(PXCCapture::STREAM_TYPE_DEPTH, mDepthSize.x, mDepthSize.y, pFPS);
````
command this line:
```
//cStatus = mSenseMgr->EnableStream(PXCCapture::STREAM_TYPE_DEPTH, mDepthSize.x, mDepthSize.y, pFPS);
```
add add this code:
```
PXCVideoModule::DataDesc desc = {};
desc.streams[PXCCapture::STREAM_TYPE_DEPTH].frameRate.min = pFPS;
desc.streams[PXCCapture::STREAM_TYPE_DEPTH].sizeMin.height = mDepthSize.y;
desc.streams[PXCCapture::STREAM_TYPE_DEPTH].sizeMin.width = mDepthSize.x;
cStatus = mSenseMgr->EnableStreams(&desc);
```
then u can get depth stream.
------------------

Do like that u can get stream, but that will not right stream.
I still research about how to resolve initialize problem now.^^

**Comment by SethGibson** [comment]
Hey all, thanks for flagging this. It's actually a pretty simple issue that's come up before having to do with differences in supported resolutions between the F200 and the R200. You can actually skip all the stream setup stuff and just make sure you're passing in a supported resolution for your hardware, i.e. 640x480 depth for the F200 and 480x360 depth for the R200. I'm going to leave this open so i remember to fix it, as I mentioned, it's come up before and I just haven't had the time to drop in the changes.

**Comment by KavinHan** [comment]
Thanks @SethGibson.
Follow u answer: I just change

```
mRSSDK->initDepth(DepthRes::R200_SD, 30, true);
```

to

```
mRSSDK->initDepth(DepthRes::F200_VGA, 30, true);
```

It's work! :)
