### ISSUE TITLE
Gaze Tracking possible?

### ISSUE THREAD

**Issue by joshuajnoble** [SethGibson/ofxRSSDKv2#4]
Hi there,

I'm trying to add Gaze Tracking into ofxRSSDKv2 on Windows 10 but I can't get anything to run without crashing mysteriously from deep within a DLL. Relevant thread https://software.intel.com/en-us/forums/realsense/topic/621869 Is there something in ofxRSSDKv2 (or OF) that precludes it from working with the Gaze Tracking module? Not really a bug, per se, more like a plea for help, any thoughts much appreciated.

**Comment by SethGibson** [comment]
Nothing I can think of off the top of my head, unless there are specific
stream settings the Gaze Tracking module requires that I haven't
implemented, and I certainly can't think of anything in OF that it would
complain about. I'll send an email up to the SDK guys and see if they have
any thoughts.

**Comment by joshuajnoble** [comment]
Cool, well thanks for taking a look. My original code was a lot more in line with OF and The rest of the addon, the code there was stripped down for ease of paste/read. The culprit seems to be QueryFace() though, bafflingly the FF_Eye example runs fine and other than not using a PXCSession to initialize the SenseManager, I basically pasted in the example.
